######################################################################
# Automatically generated by qmake (3.1) Sun May 7 20:34:05 2017
######################################################################

QT += widgets testlib


TEMPLATE = app
TARGET = testgravity
INCLUDEPATH += .
INCLUDEPATH += ..

# Input
HEADERS += testgravity.h ../graphwidget.h ../node_data.h ../node_view.h ../node_set.h
SOURCES += main.cpp testgravity.cpp ../graphwidget.cpp ../node_data.cpp ../node_view.cpp ../node_set.cpp

CONFIG += c++11
