######################################################################
# Automatically generated by qmake (3.1) Sun May 7 20:34:05 2017
######################################################################

QT += widgets


TEMPLATE = app
TARGET = gravity
INCLUDEPATH += .

# Input
HEADERS += graphwidget.h node_data.h node_view.h node_set.h
SOURCES += graphwidget.cpp main.cpp node_data.cpp node_view.cpp node_set.cpp

CONFIG += c++11
